apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-r2dbc
  namespace: spring-boot
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: spring-boot-r2dbc
      port:
        number: 80
