apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot-sa
  namespace: spring-boot
  annotations:
    iam.gke.io/gcp-service-account: spring-boot-sa@spring-boot-demo-487908.iam.gserviceaccount.com
