apiVersion: v1
kind: Service
metadata:
  name: spring-boot-r2dbc
  namespace: spring-boot
spec:
  type: NodePort
  selector:
    app: spring-boot-r2dbc
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
